database: ""
item-sets:
  lobby:
    game-selector:
      slot: 0
      material: "RECOVERY_COMPASS"
      name: "item.game_selector.name"
      lore: "item.game_selector.lore"
      command: "games"
    profile-viewer:
      slot: 1
      material: FLOWER_BANNER_PATTERN
      name: "item.profile_viewer.name"
      lore: "item.profile_viewer.lore"
      command: "profile"
    cosmetics:
      slot: 4
      material: CHEST
      name: "item.cosmetics.name"
      lore: "item.cosmetics.lore"
      command: "cosmetics"
    ride-pearl:
      slot: 5
      material: ENDER_PEARL
      name: "item.ride_pearl.name"
      lore: "item.ride_pearl.lore"
      command: "ridepearl"
    settings:
      slot: 8
      material: COMPARATOR
      name: "item.settings.name"
      lore: "item.settings.lore"
      command: "settings"