database: ""
fish-types:
  moss-fish:
    name: "fishing.moss_fish.name"
    item:
      material: PHANTOM_MEMBRANE
      custom-model-data: 1
      name: "fishing.moss_fish.item.name"
      lore: "fishing.moss_fish.item.lore"