database: ""
item-sets:
  lobby:
    game-selector:
      slot: 0
      material: "RECOVERY_COMPASS"
      name: "item.game_selector.name"
      lore: "item.game_selector.lore"
      command: "games"
    profile-viewer:
      slot: 1
      material: FLOWER_BANNER_PATTERN
      name: "item.profile_viewer.name"
      lore: "item.profile_viewer.lore"
      command: "profile"
    cosmetics:
      slot: 4
      material: CHEST
      name: "item.cosmetics.name"
      lore: "item.cosmetics.lore"
      command: "cosmetics"
    ride-pearl:
      slot: 5
      material: ENDER_PEARL
      name: "item.ride_pearl.name"
      lore: "item.ride_pearl.lore"
      command: "ridepearl"
    settings:
      slot: 8
      material: COMPARATOR
      name: "item.settings.name"
      lore: "item.settings.lore"
      command: "settings"
fish-types:
  moss-fish:
    name: fishing.moss_fish
    rarity: legendary
    item:
      material: PHANTOM_MEMBRANE
      custom-model-data: 1
      name: fishing.moss_fish.item.name
      lore: fishing.moss_fish.item.lore
  kwee-fish:
    name: fishing.kwee_fish
    rarity: rare
    item:
      material: PHANTOM_MEMBRANE
      custom-model-data: 2
      name: fishing.kwee_fish.item.name
      lore: fishing.kwee_fish.item.lore
ponds:
  pond-1:
    name: fishing.pond.kwee_pond
    description: fishing.pond.kwee_pond.description
    fishing-rod:
      material: "FISHING_ROD"
      name: "item.kwee_rod.name"
      lore: "item.kwee_rod.lore"
    weights:
      kwee-fish: 0.3
      moss-fish: 0.1
  pond-2:
    name: fishing.pond.moss_pond
    description: fishing.pond.moss_pond.description
    fishing-rod:
      material: "FISHING_ROD"
      name: "item.moss_rod.name"
      lore: "item.moss_rod.lore"
    weights:
      kwee-fish: 0.1
      moss-fish: 0.3